name: Build tailwind

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build Tailwind CSS
      run: mkdir build && npx @tailwindcss/cli -i input.css -o build/style.css
    - name: Copy files
      run: cp app.js index.html ./build
